import Head from 'next/head'
// import Image from 'next/legacy/image'
import { React } from 'react'
import IpfsComponent from '../components/ipfs'
import styles from '../styles/Home.module.css'

export default function Home () {
  // const [blockchainData, setBlockchainData] = useState()
  // const [triggerFetch, setTriggerFetch] = useState(false)
  // const [isLoading, setIsLoading] = useState(false)

  // const fetchData = () => {
  //   setIsLoading(true) // Set loading to true when fetch begins
  //   fetch('http://localhost:3001/name/streamtest20240409')
  //     .then(response => response.json())
  //     .then(data => {
  //       setBlockchainData(data)
  //       setIsLoading(false) // Set loading to false when fetch completes
  //     })
  // }

  // useEffect(() => {
  //   if (triggerFetch) {
  //     fetchData()
  //     setTriggerFetch(false) // Reset trigger
  //   }
  // }, [triggerFetch])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://unpkg.com/@helia/css@1.0.1/logos/favicon.ico" />
      </Head>

      <main>
        <IpfsComponent></IpfsComponent>
      </main>
    </div>
  )
}
